apiVersion: apps/v1
kind: Deployment
metadata:
  name: swype-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swype-app
  template:
    metadata:
      labels:
        app: swype-app
    spec:
      containers:
        - name: stripe
          image: uonyeka/stripe:linux-amd64 # Use uonyeka/stripe:linux-arm64 if you are building locally on a Mac
          ports:
            - containerPort: 5003
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "4Gi"